version: "3.9"
volumes:
    node_modules:
services:
    install_node_modules:
        image: node:18
        volumes:
            - .:/code
            - node_modules:/code/node_modules
        working_dir: /code
        entrypoint: "bash -c"
        command:
            - "yarn"
        environment:
            - HUSKY=0
    lunchbot:
        image: node:18
        depends_on:
            postgres:
                condition: service_started
            install_node_modules:
                condition: service_completed_successfully
        volumes:
            - .:/code
            - node_modules:/code/node_modules
        working_dir: /code
        entrypoint: "bash -c"
        command:
            - "yarn start"
        env_file:
            - .env
        environment:
            - TEST=asdf
        ports:
            - "3000:3000"
    postgres:
        image: postgres:14-alpine
        ports:
            - 5432:5432
        environment:
            - POSTGRES_DB=${DB_TABLE}
            - POSTGRES_PASSWORD=${DB_PASSWORD}
            - POSTGRES_USER=${DB_USER}
