version: '3.9'
services:
  lunchbot:
    image: node:18
    volumes:
      - .:/code
    working_dir: /code
    entrypoint: "bash -c"
    command:
      - "yarn && yarn start"
    env_file:
      - .env
    ports:
      - "3000:3000"
  postgres:
    image: postgres:14-alpine
    ports:
      - 5432:5432
    environment:
      - "POSTGRES_DB=${DB_TABLE}"
      - "POSTGRES_PASSWORD=${DB_PASSWORD}"
      - "POSTGRES_USER=${DB_USER}"
